import {test,expect} from '@playwright/test';

test('import, select subtopic, generate, flip, source, custom mix, reload and partial retry',async({page,request})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Create syllabus'}).click();
 await expect(page.getByRole('checkbox',{name:'Caching basics',exact:true})).toBeVisible();
 const id=(await request.get('/api/lectures').then(r=>r.json()))[0].id;
 expect((await request.get(`/api/lectures/${id}`).then(r=>r.json())).cards).toHaveLength(0);
 await page.getByRole('checkbox',{name:'Caching basics',exact:true}).check();
 await page.getByRole('button',{name:'Generate flashcards',exact:true}).click();
 await expect(page.getByText('2 cards ready to study')).toBeVisible();
 const deck=await request.get(`/api/lectures/${id}`).then(r=>r.json());
 expect(deck.cards.every((c:{primary_time:number})=>c.primary_time>=300&&c.primary_time<500)).toBe(true);
 await page.getByRole('button',{name:'Custom mix'}).click();
 await expect(page.getByRole('button',{name:'Reveal answer'})).toBeVisible();
 await page.getByRole('button',{name:'Flip card'}).click();
 const source=page.getByRole('link',{name:'Watch this explanation'});
 await expect(source).toHaveAttribute('href',/C842vFY5kRo&t=(330|350)s$/);
 await page.getByText('View supporting transcript').click();
 await expect(page.locator('blockquote')).toContainText(/cache/);
 await page.locator('body').click({position:{x:1100,y:30}});
 await page.keyboard.press('ArrowRight');
 await expect(page.getByText('2 of 2 cards')).toBeVisible();
 await expect(page.getByRole('button',{name:'Reveal answer'})).toBeVisible();
 await page.keyboard.press('Space');
 await expect(page.getByRole('button',{name:'Show question'})).toBeVisible();
 await page.reload();
 await expect(page.getByText('2 of 2 cards')).toBeVisible();
 await expect(page.getByRole('button',{name:'Show question'})).toBeVisible();
 await page.getByRole('button',{name:'Back to syllabus'}).click();
 await page.getByRole('button',{name:'Select all',exact:true}).click();
 await page.getByRole('button',{name:'Generate flashcards',exact:true}).click();
 await expect(page.getByText('Test provider interrupted the second chapter.')).toBeVisible();
 const partial=await request.get(`/api/lectures/${id}`).then(r=>r.json());
 expect(partial.cards.length).toBeGreaterThanOrEqual(3);
 expect(partial.cards.every((c:{primary_time:number})=>c.primary_time<600)).toBe(true);
 await page.getByRole('button',{name:'Retry',exact:true}).click();
 await expect(page.getByText('4 cards ready to study')).toBeVisible();
 await page.getByLabel('Study one topic').selectOption({label:'Distributed systems'});
 await expect(page.getByText('1 of 1 cards')).toBeVisible();
});
