import {useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,Layers,Sparkles,ArrowRight,Check,LoaderCircle,Clock,Shuffle,SlidersHorizontal,RefreshCw} from 'lucide-react';
import {api} from './api';
import type {Interval,LectureView,LectureSummary,StudyLaunch} from './types';
import {ImportPanel} from './features/import/ImportPanel';
import {SyllabusTree} from './features/syllabus/SyllabusTree';
import {normalizeIntervals,selectedTime,subtractIntervals,timeLabel} from './features/syllabus/selection';
import {StudyView} from './features/study/StudyView';
import {createSession,readSession,saveSession,reconcileSession} from './features/study/session';
import type {StudySession} from './features/study/session';

export default function App({hosted=false}:{hosted?:boolean}){
 const [library,setLibrary]=useState<LectureSummary[]>([]),[id,setId]=useState<string|null>(null),[lecture,setLecture]=useState<LectureView|null>(null);
 const [selection,setSelection]=useState<Interval[]>([]),[showImport,setShowImport]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[launch,setLaunch]=useState<StudyLaunch|null>(null),[videoUploadsEnabled,setVideoUploadsEnabled]=useState(false);
 const activeId=useRef(id);activeId.current=id;
 const [session,setSession]=useState<StudySession|null>(null);const resumed=useRef<string|null>(null);
 async function refresh(target:string){const result=await api.lecture(target);if(activeId.current===target){setLecture(result);if(resumed.current!==target){resumed.current=target;const saved=readSession('recall-session-'+target);if(saved&&result.cards.length){setSession(reconcileSession(saved,result.cards));setLaunch({mode:'all',intervals:[]});}}}}
 useEffect(()=>{let active=true;Promise.all([api.list(),api.health()]).then(([items,health])=>{if(!active)return;setLibrary(items);setConfigured(health.provider_configured);setVideoUploadsEnabled(health.video_uploads_enabled!==false);let preferred:string|null=null;try{preferred=sessionStorage.getItem('recall-active-lecture');}catch{}const initial=items.find(item=>item.id===preferred)||items[0];if(initial)setId(initial.id);}).catch(()=>{if(active)setError('The study service is unavailable. Try reloading in a moment.');});return()=>{active=false;};},[]);
 useEffect(()=>{setLecture(null);setSelection([]);setLaunch(null);setSession(null);resumed.current=null;setError('');if(id){try{sessionStorage.setItem('recall-active-lecture',id);}catch{}refresh(id).catch(e=>setError(e.message));}},[id]);
 const job=lecture?.jobs.find(j=>j.status==='running'||j.status==='queued')||lecture?.jobs.at(-1);
 const processing=!!job&&['running','queued'].includes(job.status);
 useEffect(()=>{if(!id||!processing)return;const timer=setInterval(()=>{refresh(id).catch(e=>setError(e.message));api.list().then(setLibrary).catch(()=>{});},2000);return()=>clearInterval(timer);},[id,processing]);
 async function imported(target:string){setShowImport(false);setId(target);setLibrary(await api.list());}
 async function action(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();if(id)await refresh(id);}catch(e){setError(e instanceof Error?e.message:'The action failed.');}finally{setBusy(false);}}
 function beginStudy(launch:StudyLaunch){if(!lecture)return;const next=createSession(lecture.cards,launch.mode,launch.intervals,launch.mode!=='topic');setSession(next);setLaunch(launch);saveSession('recall-session-'+lecture.id,next);}
 function updateSession(next:StudySession){setSession(next);if(id)saveSession('recall-session-'+id,next);}
 function exitStudy(){setLaunch(null);setSession(null);if(id)try{sessionStorage.removeItem('recall-session-'+id);}catch{}}
 const roots=lecture?.syllabus.filter(n=>!n.parent_id)||[];
 const counts:Record<string,number>={};
 if(lecture)for(const node of lecture.syllabus){const amount=lecture.cards.filter(c=>c.primary_time>=node.start&&c.primary_time<node.end).length;if(amount||lecture.completed_intervals.some(i=>i.start<node.end&&node.start<i.end))counts[node.id]=amount;}
 const selectedCards=lecture?.cards.filter(c=>selectedTime(c.primary_time,selection)).length||0;
 const selectedMinutes=Math.round(selection.reduce((sum,i)=>sum+i.end-i.start,0)/60);
 const complete=!!lecture?.duration&&subtractIntervals([{start:0,end:lecture.duration}],lecture.completed_intervals).length===0;
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/" aria-label="Recall home"><span className="brand-mark"><Layers size={23}/></span><span>recall<span className="brand-dot">.</span></span></a>
  <div className="workspace-label">YOUR STUDY SPACE</div><button className="new-lecture" onClick={()=>setShowImport(true)}><Plus size={17}/>New lecture</button>
  <div className="library-heading"><BookOpen size={14}/>Your lectures<span>{library.length}</span></div><nav aria-label="Lecture library">{library.map(item=><button key={item.id} className={`library-item ${item.id===id?'active':''}`} onClick={()=>{setId(item.id);setShowImport(false);}}><span className="lecture-icon"><BookOpen size={17}/></span><span><strong>{item.title}</strong><small>{item.duration?timeLabel(item.duration):'Preparing syllabus'}</small></span></button>)}</nav>
  {!library.length&&<p className="sidebar-empty">Your lectures will live here.<br/>Start with a video you want to learn.</p>}
  <div className="sidebar-bottom"><span className="status-dot"/>{hosted?'Saved in your private library':'Saved on this computer'}<p>Your videos. Your pace.</p></div>
 </aside><main className="main"><header className="topbar"><span><BookOpen size={16}/>Personal library</span><span className="local-badge">PERSONAL WORKSPACE</span></header><div className="main-content">
  {error&&<div className="notice error-message" role="alert">{error}</div>}
  {configured===false&&<details className="notice"><summary>Connect AI to prepare topics and generate cards</summary><p>Add your OpenAI API key to the app's local <code>.env</code> file and restart the service and worker. Credentials stay on the backend.</p></details>}
  {(showImport||(!lecture&&!id))&&<ImportPanel onImported={imported} onClose={id?()=>setShowImport(false):undefined} videoUploadsEnabled={videoUploadsEnabled}/>}
  {id&&!lecture&&!showImport&&<div className="loading"><LoaderCircle className="spin"/>Loading your lecture…</div>}
  {lecture&&!showImport&&<><div className="lecture-heading"><div><span className="eyebrow">LECTURE WORKSPACE</span><h1>{lecture.title}</h1><div className="lecture-meta"><span><Clock size={15}/>{timeLabel(lecture.duration)}</span><span><BookOpen size={15}/>{roots.length} chapters</span><span><Layers size={15}/>{lecture.cards.length} cards</span></div></div><span className="source-badge">{lecture.source_kind==='youtube'?'YouTube':'Uploaded video'}</span></div>
   {processing&&<div className="processing notice" role="status"><LoaderCircle className="spin" size={18}/><div><strong>{job?.status==='queued'?'Queued for processing':job?.stage==='generating'?'Generating your selected cards':job?.stage==='syllabus'?'Preparing chapters and subtopics':job?.stage==='transcribing'?'Transcribing the lecture':'Importing the lecture'}</strong><p>{job?.total_units?`${job.completed_units} of ${job.total_units} sections complete`:'Completed work is saved as we go.'}</p></div></div>}
   {job&&['failed','retryable'].includes(job.status)&&<div className="notice error-notice"><div><strong>{job.status==='retryable'?'Processing was interrupted':'This stage needs attention'}</strong><p>{job.error_message||'Your completed work is saved. Retry to continue.'}</p></div><button className="secondary" onClick={()=>action(()=>api.retry(job.id))} disabled={busy}><RefreshCw size={15}/>Retry</button></div>}
   {job?.error_code==='captions_unavailable'&&<div className="transcript-fallback"><label className="secondary">Attach SRT / VTT<input aria-label="Attach transcript" type="file" accept=".srt,.vtt" disabled={busy||processing} onChange={e=>{const file=e.target.files?.[0];if(file)action(()=>api.transcript(lecture.id,file));e.target.value='';}}/></label><span className="muted small">Keep this video's chapters and playback link.</span></div>}
   {!launch&&<div className="workspace-grid"><section className="syllabus-panel"><div className="panel-heading"><div><span className="eyebrow">01 · CHOOSE YOUR MATERIAL</span><h2>Your syllabus</h2></div><span className="subtle-icon"><BookOpen size={20}/></span></div><p className="panel-description">Choose a chapter or go deeper into its subtopics.</p><div className="selection-toolbar"><span>{selection.length?`${selectedMinutes} min selected`:'Select what you want to learn'}</span><div><button className="text-button" onClick={()=>setSelection(normalizeIntervals(roots.map(n=>({start:n.start,end:n.end}))))}>Select all</button><button className="text-button muted" onClick={()=>setSelection([])}>Clear</button></div></div><SyllabusTree nodes={lecture.syllabus} selected={selection} onChange={setSelection} cardCounts={counts}/><div className="generation-footer"><p><Sparkles size={15}/>Cards use only what this lecture teaches.</p><button className="primary" disabled={!selection.length||busy||processing} onClick={()=>action(()=>api.generate(lecture.id,selection))}><Sparkles size={17}/>Generate flashcards</button>{selection.length>0&&lecture.cards.length>0&&<button className="text-button" disabled={busy||processing} onClick={()=>action(()=>api.generate(lecture.id,selection,true))}>Regenerate selected material</button>}</div><p className="scope-note">Audio and captions are used. Visual-only diagrams and code may be missed.</p></section>
   <aside className="study-panel"><span className="eyebrow">02 · PUT IT INTO PRACTICE</span><h2>Make it stick.</h2><p className="muted">Pick your focus. Flip to check your recall.</p><div className="deck-illustration" aria-hidden="true"><div className="deck-back"/><div className="deck-front"><Layers size={28}/><span>YOUR FLASHCARDS</span><strong>{lecture.cards.length}</strong></div></div><div className="deck-caption">{lecture.cards.length?`${lecture.cards.length} cards ready to study`:'No cards generated yet'}</div><div className="study-options">
    <button disabled={!lecture.cards.length} onClick={()=>beginStudy({mode:'all',intervals:[]})}><span className="option-icon"><Shuffle size={18}/></span><span><strong>Mix the lecture</strong><small>{complete?'All topics together':'Includes generated topics only'}</small></span><ArrowRight size={17}/></button>
    <button disabled={!selectedCards} onClick={()=>beginStudy({mode:'custom',intervals:selection})}><span className="option-icon"><SlidersHorizontal size={18}/></span><span><strong>Custom mix</strong><small>{selectedCards?`${selectedCards} cards from your selection`:'Select topics from the syllabus'}</small></span><ArrowRight size={17}/></button>
    <label className="topic-select">Study one topic<select aria-label="Study one topic" defaultValue="" disabled={!lecture.cards.length} onChange={e=>{const node=lecture.syllabus.find(n=>n.id===e.target.value);if(node)beginStudy({mode:'topic',intervals:[{start:node.start,end:node.end}]});}}><option value="" disabled>Choose a chapter or subtopic</option>{lecture.syllabus.filter(n=>counts[n.id]>0).map(n=><option key={n.id} value={n.id}>{n.parent_id?'↳ ':''}{n.title}</option>)}</select></label>
   </div><div className="source-note"><Check size={16}/><span>Every card links back to its lecture explanation.</span></div></aside></div>}
   {launch&&session&&<StudyView session={session} cards={lecture.cards} lecture={lecture} onSessionChange={updateSession} onExit={exitStudy}/>}
   {lecture.gaps.length>0&&<details className="coverage-details"><summary>{lecture.gaps.length} coverage note{lecture.gaps.length===1?'':'s'}</summary><ul>{lecture.gaps.map(gap=><li key={gap.point_id}>{gap.reason}</li>)}</ul></details>}
  </>}
 </div><footer className="page-footer">Learn it once. Recall it often.</footer></main></div>;
}
